---
title: "Psychology of Free Will Revisited"
---

„But it is clear that ethics has nothing to do with punishment and reward in the ordinary sense. This question as to the consequences of an action must therefore be irrelevant. At least these consequences will not be events. For there must be something right in that formulation of the question. There must be some sort of ethical reward and ethical punishment, but this must lie in the action itself. Of the will as the subject of the ethical we cannot speak. And the will as a phenomenon is only of interest to psychology.“
-	Ludwig Wittgenstein, Tractatus p. 6.422 – 6.423
The groundwork of contemporary psychology is the experiment. It enables the isolation and reproduction of specific behaviours in a hand-picked sample, thought to represent the whole human population. Yet, the goal of psychology is to give account of event-unspecific, highly abstract inner functions of the mind. Wittgenstein mentions one of these: free will, necessary for ethical judgement.
Some impressive research exists (Haynes et al., 2008, Herrmann et al., 2008, Soon, Bode & Haynesa, 2013), where concrete neural signals have been successfully identified to serve as markers of an unconsciously present inclination to action.  These signals to some degree determine that a free action will take place even prior to conscious awareness of the intention to act. These Bereitscheiftspotentiale (preparedness potentials) uncovered in the work of the German psychologist Libet using the millisecond-precise electroencephalograph (EEG) (Libet et al., 1983) preclude perception of intention to act even in the magnitude of seconds, providing a viable research avenue for aspiring determinists till this day (Braun, Wessler & Friese, 2021). 
Perhaps more interestingly, similar signals popped up in my own line of work, investigating a different phenomenon, but using the same technology – EEG. As it seems, the decision to press or not to press a button on a computer is at first perceived as fairly voluntary and firmly under the control of the undertaker. However, my participants were still prone to err and experience awareness of their mistake just before making it, but too late to cancel their action. Despite having four seconds to decide whether to press a button, hardly anyone waited longer than a second. The task was rigged from the beginning, anticipating that bored participants automate their responses and experience attentional lapses as a result. Because of the automation, it is then too hard to abort a response even when attention gives a red light about an impeding mistake.
None of this is shocking. What is shocking is that the signal that came out of their heads prior to their button press, and even prior to their awareness of their own intent to press, helps to determine whether they were about to make a mistake.  This signal was unknown to them but known to the researcher. With high enough precision, it is possible to “read the mind” ahead of time and predict their decision. To extrapolate a little: in a world where the company Neuralink plans to implant microchips in people’s heads, it is conceivable to measure the signal so precisely that we would really have access to information enabling the prediction of people’s actions.
Naïve proponents of free will often employ the readily available example of being able to spontaneously move one’s finger. Surely, I have free will if I can move whenever I please. But if a subconscious neural convulsion is present even prior to my spontaneous decision to move, am I just under an illusion of that freedom? The most common-sense intuition about free will is in trouble.
The examples provided show that scientists do get some results if they average highly sterile trials carefully fashioned to be alike and where all subjects constrain their behaviour to align with a carefully managed research aim. In these cases, we must accept that will-as-a-phenomenon is partly explained away. 
On the contrary, we can abide by Wittgenstein’s distinction and challenge the determinist story as based on constrained laboratory environment which cannot contribute anything at all to knowledge of free will. Instead, it produces but parodic doxa: shadows which occasionally correlate, sometimes by accident, with the true underlying mental faculty of free will. What tragedy if a shadow were mistaken for reality and were treated so. An ethical decision stripped of its freedom becomes explainable, and so, conditional.
To propose an argument for free will, I will start with Elisabeth Anscombe’s thought exercise (Anscombe, 1957): When driving my car, I see a person walking over the street. I firmly press on the pedal and run the person over. “Why” did I run the person over? Because I had a subconscious inkling seen in my Bereitshaftspotential 500ms prior, which then moved me to decide to operate my motor cortex and so bring my leg into motion, pressing the pedal. It is comparable to an act in a laboratory when one spontaneously presses a button or moves a finger. In a social setting, or at court, such answer is not only insufficient; it is asocial mockery. 
One more example, consider this scene where Meursault shoots an Arab in The Stranger:
A shaft of light shot upward from the steel, and I felt as if a long, thin blade transfixed my forehead. At the same moment all the sweat that had accumulated in my eyebrows splashed down on my eyelids, covering them with a warm film of moisture. Beneath a veil of brine and tears my eyes were blinded; I was conscious only of the cymbals of the sun clashing on my skull, and, less distinctly, of the keen blade of light flashing up from the knife, scarring my eyelashes, and gouging into my eyeballs. Then everything began to reel before my eyes, a fiery gust came from the sea, while the sky cracked in two, from end to end, and a great sheet of flame poured down through the rift. Every nerve in my body was a steel spring, and my grip closed on the revolver. The trigger gave, and the smooth underbelly of the butt jogged my palm (McCarthy, 2004).
No. I run the person over (conclusion), because I hated him (premise 1), and revenge is best served cold (premise 2). Such an explanation exhausts the “why” question. Pure description of any event forming the execution of that well-deliberated judgement, even if highly intricate, fails to do so.
Likewise, a participant in a Bereitshaftspotential experiment is really just acting out one ethical judgment: to take part in an experiment and comply. So was the case for my participants. What I can tell from qualitative data, their intention was mostly to help me, with a bonus of earning £13. This is why they pressed the button and this is why their central beta oscillatory power subconsciously increased, prior to a button press.
And so, the main mistake a determinist makes is that they confuse one average of explanatively insufficient behaviours with one case of explanatively satisfactory behaviour, which turns out to be always experimentally unmeasurable.
Just for the sake of professionality, I would like to address at least one objection to the argument, but I encourage you to consider more should you wish to defend free will. A prospective gap in this reasoning is that several intentions or higher-order explanations at once are possible for the fact at hand. I may not only be enacting vengeance, I could also be in a great rush to the airport. To answer the objection, the principle of sufficient reason can be invoked: intentions are combined, some diminishing and some increasing the chance for me to decide one way or another. One final explanation may not exhaust the entirety of my reasoning at the time, but it is sufficient to give a consistent meaning to the act. Running someone over as a planned act of vengeance is more sufficient as an explanation than negligence in travel to the airport, especially in light of any further unmentioned but likely evidence.
So, how can empirical psychologists study free will? Using experiments, not very much. Not without getting into trouble with ethics committees as our predecessors did (Milgram, 1963). Yet, resignation on the experimental method and retained insistence on scientific basis of psychological research may lead psychologists down a path of self-promotion under the guise of scientist, using the décor of science, without using its principles (Cremer, 2023). 
Better to keep the experimental method, but then admit that whereof one cannot speak, thereof one must be silent. Alternatively, let us admit that psychology as empirical science is always guided by psychology as a philosophical study of a human person. Otherwise, we’d have to try and sell the relevance of a highly unsatisfactory field of neurobehavioural studies, where we discuss modest correlations between specific isolated moments of laboratory sessions of mostly twenty-something psychology students sitting in silence to press buttons now and then and where barely detectable increases and decreases in brain activity in some of them explain some of that button clicking.
References
Anscombe, G. E. M. (1957). intention. Blackwell.
Braun, M. N., Wessler, J., & Friese, M. (2021). A meta-analysis of libet-style experiments. Neuroscience and Biobehavioral Reviews, 128, 182-198. https://doi.org/10.1016/j.neubiorev.2021.06.018
Cremer, T. (2023;2021;). A religious vaccination? how christian communities react to right-wing populism in germany, france and the US. Government and Opposition (London), 58(1), 162-182. https://doi.org/10.1017/gov.2021.18
Haynes, J., Soon, C. S., Brass, M., & Heinze, H. (2008). Unconscious determinants of free decisions in the human brain. Nature Neuroscience, 11(5), 543-545. https://doi.org/10.1038/nn.2112
Herrmann, C. S., Pauen, M., Min, B., Busch, N. A., & Rieger, J. W. (2008;2007;). Analysis of a choice-reaction task yields a new interpretation of libet's experiments. International Journal of Psychophysiology, 67(2), 151-157. https://doi.org/10.1016/j.ijpsycho.2007.10.013
Libet, B., Gleason, C. A., Wright, E. W., & Pearl, D. K. (1983). Time of conscious intention to act in relation to onset of cerebral activity (readiness-potential). The unconscious initiation of a freely voluntary act. Brain : a journal of neurology, 106 (Pt 3), 623–642. https://doi.org/10.1093/brain/106.3.623
McCarthy, P., & ProQuest (Firm). (2004). Albert Camus, the Stranger (2nd ed.). Cambridge University Press.
Milgram, S. (1963). behavioral study of obedience. Journal of Abnormal Psychology (1965), 67, 371. https://doi.org/10.1037/h0040525
Soon, C. S., HE, A. H., Bode, S., & Haynesa, J. (2013). Predicting free choices for abstract intentions. Proceedings of the National Academy of Sciences - PNAS, 110(15), 6217-6222. https://doi.org/10.1073/pnas.1212218110
Wittgenstein, L., Pears, D. F., McGuinness, B., & Russell, B. (2014). Tractatus logico-philosophicus. Routledge. https://doi.org/10.4324/9781315884950
