---
title: "Simon Hanzal"
---
I am a postgraduate student at the University of [Glasgow’s Institute of Neuroscience and Psychology](https://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/). I work with [Dr Monika Harvey](https://www.gla.ac.uk/schools/psychology/staff/monikaharvey/), [Prof Gregor Thut](https://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/staff/gregorthut/) and [Dr Gemma Learmonth](https://gemmalearmonth.com/).

# Introduction

My main topic of interest is attention and its role in various neurological disorders. Previously, I studied emotion and music-evoked autobiographical memories through public engagement. Insights from the project provide an improvement to the guidelines in therapeutic interventions for patients with a range of neurocognitive disorders. I am currently interested in the use of non-invasive electroencephalography (EEG) in neurofeedback therapy to relieve post-stroke fatigue and improve attention in stroke patients. 

# Academic History

## Present

## University of Glasgow

### Research Methods of Psychological Science (MSc)
* Type of study: Full-time
* Dates: September 2020 – Present
* Education Duration: 2 mos
* Dissertation: TBC
* Courses: Data Skills for Reproducible Science, Introduction to MatLab Programming, Professional Skills, Qualitative Methods, Research Methods in Cognitive Science, Cognitive Brain Imaging Methods, Statistics & Research Design

### Single Honours Psychology (MA)
* Type of study: Full-time
* Dates: September 2016 – August 2020
* Education Duration: 4 years
* Dissertation: Investigation of alpha rhythms during phasic alerting in young and older adults
* Honours courses: Cognitive Psychology, Human Development, Perception Vision Cognition, Professional Skills, Social Psychology, Statistics, Individual Differences, Qualitative Mini Project, Quantitative Mini Project, Physiological Psychology, Psychometrics, Virtue Ethics, Cognitive Neuroscience: Insights into Brain Plasticity, Neuropsychological Deficits, Sleep and Circadian Timing, Neuroscience of Decision Making, From Visual Awareness to Free Will, Current Trends in Clinical Psychology, Health Neuroscience.

# Experience

## Resesarch

### Research Scientist, Summer Intern
* Employment: Full-time
* Dates Employed: Jun 2018 – Jul 2018
* Employment Duration: 2 mos
* Optimising music listening interventions for individuals with neurological conditions.
* Responsibilities:

## Volunteering

### Volunteer
* Charity: Legion of Mary Scotland
* Dates: December 2017 - Present
* Duration: 3 years
* Job Description: Visiting a soup kitchen for the homeless to engage with the patrons, providing community education.

### Volunteer
* Charity: Shelter Scotland
* Dates: January 2017 - May 2015
* Duration: 5 Months
* Job Description: Fundraising and maintanance of charity shop

### Volunteer
* Charity: Diakonie ČCE
* Dates: August 2015 - March 2016
* Duration: 1 tear, 3 Months
* Job Description: Visitting a day-care centre for service users with physical and mental disability to accompany, play music and engage with the service users.

### Volunteer
* Charity: Caritas Czech Republic
* Dates: January 2014 - March 2015
* Duration: 1 tear, 3 Months
* Job Description: Visitting a pallitative care ward to provide care and company to the patients.

# Skills

## Licences and Certifications

### Psychological First Aid Course Certificate
* Issuer: John Hopkins University
* Date Issued: April 2020

### PVG Scheme Membership
* Issuer: Disclosure Scotland
* Date Issued: January 2019

### Goethe-Zertifikat B2
* Issuer: Goethe-Institut e.V.
* Issued: October 2015

### Cambridge Certificate of Proficiency in English C2
* Issuer: Cambridge Assessment International Education
* Issued: January 2015

## Technical Skills

* R programming language (advanced proficiency)
* MS Office (Full working proficiency)
* Web Programming (basic working proficiency)
* Python (elementary proficiency)

## Languages

* Czech (Native proficiency)
* English (Full professional proficiency) C2
* Polish (Limited working proficiency) B2
* German (Limited working proficiency) B2
* Russian (Elementary Proficiency) A2

# Funding and Awards

## Public Engagement Award
* Issuer: College of Medical,Veterinary & Life Sciences, University of Glasgow
* Date: December 2019
* For: Summer Research Project

## £2000 Biomedical Vacation Scholarship
* Issuer: Wellcome Trust
* Date: May 2019
* For: Summer Reserach Project

## Certificate of Academic Excellence
* Issuer: School of Psychology, University of Glasgow
* Date: January 2017
* Foor: Course performance

# Links

### Articles

* [The forced loneliness of coronavirus lockdowns](https://the-gist.org/2020/09/the-forced-loneliness-of-coronavirus-lockdowns/) in Glasgow Insight into Science & Technology.